export const federatedMarketPlaceItemWidth = "150";
export const federatedMarketPlaceProductWidth = "180";
export const federatedMarketPlaceProductHeight = "200";
export const federatedMarketPlaceResourceWidth = "180";
export const federatedMarketPlaceResourceHeight = "220";

export const IOTFEDS_VERTICALS = "IOTFEDS_VERTICALS";
export const IOTFEDS_RESOURCES = "IOTFEDS_RESOURCES";
export const IOTFEDS_OBSERVED_PROPERTIES = "IOTFEDS_OBSERVED_PROPERTIES";
export const IOTFEDS_PLATFORMS = "IOTFEDS_PLATFORMS";
export const IOTFEDS_DESCRIPTIONS = "IOTFEDS_DESCRIPTIONS";
export const IOTFEDS_PRODUCT_NAMES = "IOTFEDS_PRODUCT_NAMES";
export const IOTFEDS_MIN_PRICE  = "IOTFEDS_MIN_PRICE";
export const IOTFEDS_MAX_PRICE  = "IOTFEDS_MAX_PRICE";
export const IOTFEDS_MAX_TRUST  = "IOTFEDS_MAX_TRUST";
export const IOTFEDS_MIN_TRUST  = "IOTFEDS_MIN_TRUST";
export const IOTFEDS_LOCATIONS  = "IOTFEDS_LOCATIONS";
export const IOTFEDS_SELLER_IDS = "IOTFEDS_SELLER_IDS";

export const IOTFEDS_LONGITUDE       = "IOTFEDS_LONGITUDE";
export const IOTFEDS_LATITUDE        = "IOTFEDS_LATITUDE";
export const IOTFEDS_MAX_DISTANCE    = "IOTFEDS_RADIUS";

export const  IOTFEDS_MIN_REPUTATION = "IOTFEDS_MIN_REPUTATION";
export const  IOTFEDS_MAX_REPUTATION = "IOTFEDS_MAX_REPUTATION";

export const IOTFEDS_RECOURCE_NAMES                = "IOTFEDS_RECOURCE_NAMES";
export const IOTFEDS_RESOURCE_DESCRIPTIONS         = "IOTFEDS_RESOURCE_DESCRIPTIONS";
export const IOTFEDS_RESOURCE_ADAPTIVE_TRUST       = "IOTFEDS_RESOURCE_ADAPTIVE_TRUST";
export const IOTFEDS_RESOURCE_OBSERVED_PROPERTIES  = "IOTFEDS_RESOURCES_OBSERVED_PROPERTIES";
export const IOTFEDS_RESOURCE_FEDERATION           = "IOTFEDS_RESOURCE_FEDERATION";

export const IOTFEDS_RESOURCE_RESOURCE_TRUST       = "IOTFEDS_RESOURCE_RESOURCE_TRUST";
export const IOTFEDS_RESOURCE_RESOURCE_TYPE        = "IOTFEDS_RESOURCE_RESOURCE_TYPE";
export const IOTFEDS_RESOURCE_NAMES                = "IOTFEDS_RESOURCE_NAMES";
export const IOTFEDS_RESOURCE_IDS                  = "IOTFEDS_RESOURCE_IDS";
export const IOTFEDS_PLATFORM_ID                   = "IOTFEDS_PLATFORM_ID";
export const IOTFEDS_STREAMING                     = "IOTFEDS_STREAMING";

export const  IOTFEDS_NAME_OF_PRODUCT         = "IOTFEDS_NAME_OF_PRODUCT";
export const  IOTFEDS_DETAILS_OF_PRODUCT      = "IOTFEDS_DETAILS_OF_PRODUCT";
export const  IOTFEDS_DESCRIPTIONS_OF_PRODUCT = "IOTFEDS_DESCRIPTIONS_OF_PRODUCT";
export const  IOTFEDS_VERTICALS_OF_PRODUCT    = "IOTFEDS_VERTICALS_OF_PRODUCT";
export const  IOTFEDS_PLATFORM_NAMES          = "IOTFEDS_PLATFORM_NAMES";


export const  IOTFEDS_PRODUCT_PURCHASED_FROM = "IOTFEDS_PRODUCT_PURCHASED_FROM";
export const  IOTFEDS_PRODUCT_PURCHASED_TO   = "IOTFEDS_PRODUCT_PURCHASED_TO";
export const  IOTFEDS_PRODUCT_ID             = "IOTFEDS_PRODUCT_ID";





export const  NOT_DEFINED_YET = -1;

export const labelColor1 = "#000080";
export const inputBorderColor1 = "#FF0000";
export const widthOfBorder = "0px";





